### ISSUE TITLE
Change CF metabox title

### ISSUE THREAD

**Issue by jquimera** [Jpwaldstein/carbon-fields-page-builder#1]
Hello, I'm using the wonderful Carbon Fields in my project. I have a text field to place a title, and would like that when the text field was filled in, the metabox's tag would be changed by it.

`Field::make('text', 'main_block_title',__('Block Title', 'textdomain'))
`
My English is bad, so I took a picture for an example.

![example](http://i.imgur.com/MnSmXOg.jpg)

Could you help me?

**Comment by jonwaldstein** [comment]
Hi @jquimera , this repo is just an add-on for Carbon Fields.  You will want to contact Carbon Fields Directly - https://github.com/htmlburger/carbon-fields
